#!/bin/bash

#CURRENT_SPACE=( $(yabai -m query --spaces | jq '.[] | select(."has-focus" == true) | .index') )
INDEX=$1

#if [[ $INDEX == 1 && $CURRENT_SPACE == 1 ]]; then
#  yabai -m space --focus prev || yabai -m space --focus last
#else
  yabai -m space --focus $1
#fi
