#!/usr/bin/env python3

# pip3 install iterm2
# pip3 install pyobjc

import iterm2
import AppKit

AppKit.NSWorkspace.sharedWorkspace().launchApplication_("iTerm2")

async def main(connection):
    app = await iterm2.async_get_app(connection)
    await app.async_activate()
    iterm2.Window.async_create(connection)

iterm2.run_until_complete(main, True)
